# Generated by Django 4.1.13 on 2025-09-25 07:58

from django.db import migrations, models
import systemuser.models


class Migration(migrations.Migration):

    dependencies = [
        ('systemuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='user_image',
            field=models.ImageField(default='profile_pic/image.jpg', upload_to=systemuser.models.image_path),
        ),
    ]
